version: "3.8"

services:
  admin-portal:
    build: .
    image: admin-portal:v2.6
    container_name: admin-portal
    environment:
      - PCO_CONFIG_DIR
      - PCO_DATA_DIR
      - PCO_LOGS_DIR
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - OIDC_DISCOVERY_URL
      - TZ=America/Chicago
    restart: unless-stopped
    ports:
      - "7365:7365"
    volumes:
      - ${PCO_CONFIG_DIR:-./config}:/app/config
      - ${PCO_DATA_DIR:-./data}:/app/data
      - ${PCO_LOGS_DIR:-./logs}:/app/logs
